title: Recognize Machine Learning
description: > # this means to ignore newlines until "baseurl:"
  I'll show you the different approach to understand machine learning,
  from my perspective that will make you interested.
permalink: ':title/'
baseurl: "/rakka-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rakka Alhazimi # add your name
author-img: rakka-alhazimi.jpg # add your photo
about-author: I am a self-taught programmer who focused on Machine Learning with Python. # add description
social-twitter: AlhazimiRakka # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rakkaalhazimi # add your Github handle
social-linkedin: rakka-alhazimi-707848198 # add your Linkedin handle
social-email: rakkakeren@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
